name: deploy

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Cache cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-${{ runner.os }}

      - name: Setup | Cache build
        uses: actions/cache@v3
        with:
          path: ./target
          key: target-${{ runner.os }}-${{ github.run_id }}
          restore-keys: target-${{ runner.os }}

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Deploy | Package ncmdump
        run: cargo package --package ncmdump

      - name: Deploy | List ncmdump packaged files
        run: cargo package --package ncmdump --list

      - name: Deploy | Publish npmdump
        run: cargo publish --package ncmdump --token ${{secrets.crate_token}}

      - name: Deploy | Package ncmdump-bin
        run: cargo package --package ncmdump-bin

      - name: Deploy | List ncmdump-bin packaged files
        run: cargo package --package ncmdump-bin --list

      - name: Deploy | Publish npmdump-bin
        run: cargo publish --package ncmdump-bin --token ${{secrets.crate_token}}
